package com.sundy.common.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.sundy.common.bean.SubscribeBean;

import com.sundy.common.db.SubscribeBeanDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig subscribeBeanDaoConfig;

    private final SubscribeBeanDao subscribeBeanDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        subscribeBeanDaoConfig = daoConfigMap.get(SubscribeBeanDao.class).clone();
        subscribeBeanDaoConfig.initIdentityScope(type);

        subscribeBeanDao = new SubscribeBeanDao(subscribeBeanDaoConfig, this);

        registerDao(SubscribeBean.class, subscribeBeanDao);
    }
    
    public void clear() {
        subscribeBeanDaoConfig.clearIdentityScope();
    }

    public SubscribeBeanDao getSubscribeBeanDao() {
        return subscribeBeanDao;
    }

}
